databases:
  - name: tadoku-kun-db
    databaseName: tadoku_kun_production
    user: tadoku_kun

services:
  - type: web
    name: tadoku-kun
    env: ruby
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:create db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tadoku-kun-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_MASTER_KEY
        generateValue: true